# -*- coding: utf-8 -*-
"""bag_of_words.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yhpyDVufTsMP7eAgcDZQqh8aTEergNqB
"""

from collections import Counter
import os

import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')

from google.colab import drive
drive.mount('/content/gdrive')

flattened_files_dir = '/content/gdrive/My Drive/Colab Notebooks/Science Machine/science_machine_repo/data/2_flattened/flattened_from_xml/'
for file_name in os.listdir(flattened_files_dir):
    file_path = flattened_files_dir + file_name
    with open(file_path, 'r') as f:
        contents = f.read().lower()
        words = contents.split()
        words = [word for word in words if word not in set(stopwords.words('english'))] # filter stop_words
        print(Counter(words).most_common(20))


'''
Output:

[('unconscious', 111), ('perception', 75), ('states', 68), ('conscious', 47), ('perceptual', 46), ('(e.g.', 46), ('one', 44), ('evidence', 43), ('participants', 39), ('.', 37), ('would', 35), ('visual', 35), ('phillips', 31), ('may', 31), ('consciousness', 29), ('stimuli', 28), ('without', 27), ('example,', 27), ('perception.', 25), ('p&amp;l', 25)]
[('x', 149), ('consciousness', 96), ('machine', 70), ('test', 65), ('.', 45), ('tests', 44), ('human', 40), ('academic', 34), ('turing', 34), ('&amp;', 33), ('use', 31), ('personal', 30), ('--not', 30), ('reproduction', 30), (',', 30), ('imprint', 30), ('2019', 29), ('(c)', 29), ('copyright', 27), ('one', 23)]
[('sensory', 26), ('mid-level', 25), ('states', 23), ('might', 23), ('consciousness', 21), ('beliefs', 20), ('qualia', 19), ('world', 18), ('inference', 17), ('use', 16), ('certain', 16), ('kind', 15), ('hierarchical', 14), ('see', 13), ('experience', 12), ('phenomenal', 12), ('generative', 12), ('patterns', 12), ('highly', 12), ('2019', 11)]
'''


        
! cd "/content/gdrive/My Drive/Colab Notebooks/Science Machine/science_machine_repo/code/analysis"; git add bag_of_words.ipynb; git status; git diff --cached; git commit -m "Add bag_of_words.ipynb notebook."; git push origin master

! ssh-keygen

! cat ~/.ssh/id_rsa.pub

! cd "/content/gdrive/My Drive/Colab Notebooks/Science Machine/science_machine_repo/code/analysis"; git remote -v;   git push origin master

! cat ~/.ssh/id_rsa.pub

